
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import HeaderNav from '@/components/nav/HeaderNav'
import { Toaster } from 'react-hot-toast'
import { AuthProvider } from '@/context/auth'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <AuthProvider>
          <Toaster />
          <HeaderNav />
          {children}
        </AuthProvider>

      </body>
    </html>
  )
}
